import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [res, setRes] = useState(null);
  useEffect(() => {
    fetch('/api/query')
      .then((res) => res.json())
      .then((res) => setRes(res));
  });
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <ul>
          <li>Name: {res?.name}</li>
          <li>Map: {res?.map}</li>
          <li>Game: {res?.game}</li>
          <li>Version: {res?.version}</li>
          <li>Online Players: {res?.players.length}</li>
          <li>Max Players: {res?.maxplayers}</li>
        </ul>
      </main>
    </>
  )
}
